### ISSUE TITLE
input要素を上下中央に移動させたい

### ISSUE THREAD

**Issue by Tebaeleven** [Tebaeleven/svg_blocks#5]
# 現在のコード
```html
        <foreignObject x="18" y="10" width="30" height="20" >
            <input type="text" id="input-size" value="名刺" ">
        </foreignObject>
```
```css
foreignObject{
    background-color:rgb(255, 255, 255);
    vertical-align: middle;
    
}
foreignObject input{
    background-color:transparent;
    border: none;
    outline: none;
    background: blue;
}
```
